/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaDeRepeticaoAvancada;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        String nomeDoProduto;
        float precoCusto;
        float precoVenda;
        
        float totalCusto = 0.0f;
        float totalVenda = 0.0f;
        
        Scanner leitor = new Scanner(System.in);
        
        int i = 0;
        for (; i <= 10; i++){
            System.out.println("Digite o nome do produto");
            nomeDoProduto = leitor.next();
            
            System.out.println("Digite o preço de custo do produto");
            precoCusto = leitor.nextFloat();
            
            System.out.println("Digite o preço de venda do produto");
            precoVenda = leitor.nextFloat();
            
            totalCusto = totalCusto + precoCusto;
            totalVenda = totalVenda + precoVenda;
            
            if(precoCusto == precoVenda){
                System.out.println("Houve um empate entre o preço de custo e preço de venda");
            } else {
                if(precoCusto > precoVenda){
                    System.out.println("Houve prejuízo");
                } else {
                    System.out.println("Houve lucro");
                }
            }
            
            System.out.println(nomeDoProduto + ", preço de custo = " + precoCusto +
                    ", oreço de venda = " + precoVenda);
        }
        
        System.out.println("A média do preço de custo é de: " + (totalCusto / i));
        System.out.println("A média do preço de venda é de: " + (totalVenda / i));
        
        
    }
}
